<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>

<h2>product add</h2>
<form method="post" action="">
<div>
    name
<input type="text" name="name">
</div>
<div>
    description
<input type="text" name="description">
</div>
<div>
    tag
<input type="text" name="tags">
</div>
<div>
    price
<input type="text" name="price">
</div>
<div>
    stock
<input type="text" name="stock">
</div>
<div>
<input type="submit" name="submit" value="add" >
</div>
</form>

<div>

<a href="orderadd">add order</a>
  <a href="setting">settings</a>
  <a href="productadd">addproduct</a>
  <a href="orderlist">list order</a>
  <a href="productlist">list product</a>
</div>
  
</body>
</html>