<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

    <h2>setting </h2>
    <form method="post" action="">
        <div>

            <label for="title_optimization
"> title optimization
            </label>
            <select name="optimization" id="color">
                <!-- <option value="">--- Choose  ---</option> -->
                <option value="Y">With tags</option>
                <option value="N">Without tags</option>
                <!-- <option value="blue">Blue</option> -->
            </select>
            <!-- <input type="text" name="name"> -->
        </div>
        <div>
            Default Price
            <input type="number" name="Default_Price">
        </div>
        <div>
            default zip
            <input type="text" name="   default_zip">
        </div>

        <div>
            default stock
            <input type="number" name="default_stock">
        </div>
        <div>
            <input type="submit" name="submit" value="save">
        </div>
    </form>

    <div>

    <a href="orderadd">add order</a>
<a href="setting">settings</a>
<a href="productadd">addproduct</a>
    </div>

</body>

</html>