<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
<form method="post" action="/acl/adduser?role=<?php echo $this->request->getQuery('role'); ?>" >

    <div>
        name
        <input type="text" name="name" placeholder="username">
    </div>
    <div>
        password
        <input type="password" name="password" placeholder="password">
    </div>

    <div>
        <label for="products"> controller</label>
        <select name="role" id="role">

            <?php
            // print_r($message);
            // echo $message;

            $str = "";

            for ($i = 0; $i < count($message); $i++) {

                $str .= '<option value="' . $message[$i]->role . '">' . $message[$i]->role . '</option>';
            }

            echo $str

            ?>

        </select>

        <input type="submit" name="submit" value="add">
    </div>
    </form>
</body>

</html>